#!/bin/sh

# DESCRIPTION:
#   Install packages via "apt" and remove useless stuff.
#   Retries twice if the install fails to avoid failing because of unstable network.
#   You should use this mainly in Docker builds to easily get smaller final images.
# USAGE:
#   install_packages <package_1> <package_2> ... <package_n>
# BASED ON:
#   https://github.com/bitnami/containers/blob/main/bitnami/nginx/1.23/debian-11/prebuildfs/usr/sbin/install_packages

set -eu

n=0
max=2
export DEBIAN_FRONTEND=noninteractive

until [ $n -gt $max ]; do
    set +e
    (
      apt-get update -qq &&
      apt-get install -y --no-install-recommends "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "apt failed, retrying"
    n=$(($n + 1))
done
apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
