#!/bin/bash

# DESCRIPTION:
#   Print a "rainbow coloured random cowsay option" saying something.
#   Note that you need "lolcat" installed to run this. In newer Ubuntu versions, it's in the standard apt repository.
#   Here's the Github to it: https://github.com/busyloop/lolcat
# USAGE:
#   Use the examples below and see the magic happen:
#   ./rainbow-cowsay echo -n "Hello World!"
#   ./rainbow-cowsay fortune
#    To make it run whenever you open your terminal, put a line with a call to this script at the end of your "~/.bashrc".

input=("$@")

main(){
    # Store command output in array: https://stackoverflow.com/a/11426834
    local options=( "$(
        # List all "cowsay" options
        for file in /usr/share/cowsay/cows/*.cow; do
            # Remove ".cow" from the files names
            basename "$file" .cow
        done
    )" )

    # Select random item of array in bash: https://stackoverflow.com/a/2388555
    local random_option="${options[ $RANDOM % ${#options[@]} ]}"

    # Make your input *~fabulous~*
    "${input[@]}" | cowsay -f "$random_option" | lolcat
}

main

exit 0
