#!/bin/bash

# DESCRIPTION:
#   Print a "rainbow coloured random cowsay option" saying something.
#   Note that you need "lolcat" installed to run this. In newer Ubuntu versions, it's in the standard apt repository.
#   Here's the Github to it: https://github.com/busyloop/lolcat
# USAGE:
#   Use the examples below and see the magic happen:
#   ./rainbow-cowsay echo -n "Hello World!"
#   ./rainbow-cowsay fortune
#    To make it run whenever you open your terminal, put a line with a call to this script at the end of your "~/.bashrc".

cows="( $(cowsay -l | sed '1d') )"

# Select random item of array in bash: https://stackoverflow.com/a/2388555
random_cow=${cows[$RANDOM % ${#cows[@]}]}

# Make your input *~fabulous~*
"$@" | cowsay -f "$random_cow" | lolcat

exit 0
