#!/bin/sh

# DESCRIPTION
#   Recreate VMs with Vagrant and do additional config to enable connection right away.
#   Note that you first need to create the ssh keys and configure the Vagrantfile.
# USAGE
#   ./vm-recreate.sh <vm_1> <vm_2> ... <vm_n>

set -eu

ssh_port=22

# Checks Vagrantfile
if [ ! -e Vagrantfile ]; then
	echo "Vagrantfile is missing!" >&2
	exit 1
fi

# Recreate VMs
vagrant destroy --force
vagrant up

for vm in "$@"; do
	# Removes previous known_hosts entries
	ssh-keygen -f "${HOME}/.ssh/known_hosts" -R "${vm}"

	# Awaits VM ssh port availability
	until nc -z -w2 "${vm}" "${ssh_port}"; do
		echo "Awaiting ${vm}..."
		sleep 2
	done

	# Tests connection
	# -n: Dry run
	# -o StrictHostKeyChecking=accept-new: Skips prompt to accept connection
	ssh -n -o StrictHostKeyChecking=accept-new "vagrant@${vm}" >/dev/null 2>&1
done

exit 0
