name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Run Make
        run: make
