name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-jammy
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.4.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Makefile') }}

      - name: Run tests
        run: make
